### ISSUE TITLE
Change page titles

### ISSUE THREAD

**Issue by AbumattarSA** [W8-Recipedia/Recipedia#46]
Update the titles on each page to include the name of the website, e.g. change 'Home' to 'Recipedia | Home' and 'Settings' to 'Recipedia | Settings'.

![image](https://user-images.githubusercontent.com/40639965/108531507-a874fa00-72ce-11eb-99f0-3f8f945fb2e4.png)

**Comment by tutugan** [comment]
finished the task,hopefully also commited (starting to get it but not 100% sure)
